// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.35.1
// 	protoc        v5.28.3
// source: proto/vanna/vanna.proto

package vanna

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GenerateSQLRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Question string            `protobuf:"bytes,1,opt,name=question,proto3" json:"question,omitempty"`
	Context  map[string]string `protobuf:"bytes,2,rep,name=context,proto3" json:"context,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
}

func (x *GenerateSQLRequest) Reset() {
	*x = GenerateSQLRequest{}
	mi := &file_proto_vanna_vanna_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateSQLRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateSQLRequest) ProtoMessage() {}

func (x *GenerateSQLRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_vanna_vanna_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateSQLRequest.ProtoReflect.Descriptor instead.
func (*GenerateSQLRequest) Descriptor() ([]byte, []int) {
	return file_proto_vanna_vanna_proto_rawDescGZIP(), []int{0}
}

func (x *GenerateSQLRequest) GetQuestion() string {
	if x != nil {
		return x.Question
	}
	return ""
}

func (x *GenerateSQLRequest) GetContext() map[string]string {
	if x != nil {
		return x.Context
	}
	return nil
}

type GenerateSQLResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Sql         string `protobuf:"bytes,1,opt,name=sql,proto3" json:"sql,omitempty"`
	Explanation string `protobuf:"bytes,2,opt,name=explanation,proto3" json:"explanation,omitempty"`
}

func (x *GenerateSQLResponse) Reset() {
	*x = GenerateSQLResponse{}
	mi := &file_proto_vanna_vanna_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateSQLResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateSQLResponse) ProtoMessage() {}

func (x *GenerateSQLResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_vanna_vanna_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateSQLResponse.ProtoReflect.Descriptor instead.
func (*GenerateSQLResponse) Descriptor() ([]byte, []int) {
	return file_proto_vanna_vanna_proto_rawDescGZIP(), []int{1}
}

func (x *GenerateSQLResponse) GetSql() string {
	if x != nil {
		return x.Sql
	}
	return ""
}

func (x *GenerateSQLResponse) GetExplanation() string {
	if x != nil {
		return x.Explanation
	}
	return ""
}

type ValidateSQLRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Sql string `protobuf:"bytes,1,opt,name=sql,proto3" json:"sql,omitempty"`
}

func (x *ValidateSQLRequest) Reset() {
	*x = ValidateSQLRequest{}
	mi := &file_proto_vanna_vanna_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateSQLRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateSQLRequest) ProtoMessage() {}

func (x *ValidateSQLRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_vanna_vanna_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateSQLRequest.ProtoReflect.Descriptor instead.
func (*ValidateSQLRequest) Descriptor() ([]byte, []int) {
	return file_proto_vanna_vanna_proto_rawDescGZIP(), []int{2}
}

func (x *ValidateSQLRequest) GetSql() string {
	if x != nil {
		return x.Sql
	}
	return ""
}

type ValidateSQLResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	IsValid bool   `protobuf:"varint,1,opt,name=is_valid,json=isValid,proto3" json:"is_valid,omitempty"`
	Message string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *ValidateSQLResponse) Reset() {
	*x = ValidateSQLResponse{}
	mi := &file_proto_vanna_vanna_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateSQLResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateSQLResponse) ProtoMessage() {}

func (x *ValidateSQLResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_vanna_vanna_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateSQLResponse.ProtoReflect.Descriptor instead.
func (*ValidateSQLResponse) Descriptor() ([]byte, []int) {
	return file_proto_vanna_vanna_proto_rawDescGZIP(), []int{3}
}

func (x *ValidateSQLResponse) GetIsValid() bool {
	if x != nil {
		return x.IsValid
	}
	return false
}

func (x *ValidateSQLResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type ExplainSQLRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Sql string `protobuf:"bytes,1,opt,name=sql,proto3" json:"sql,omitempty"`
}

func (x *ExplainSQLRequest) Reset() {
	*x = ExplainSQLRequest{}
	mi := &file_proto_vanna_vanna_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExplainSQLRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExplainSQLRequest) ProtoMessage() {}

func (x *ExplainSQLRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_vanna_vanna_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExplainSQLRequest.ProtoReflect.Descriptor instead.
func (*ExplainSQLRequest) Descriptor() ([]byte, []int) {
	return file_proto_vanna_vanna_proto_rawDescGZIP(), []int{4}
}

func (x *ExplainSQLRequest) GetSql() string {
	if x != nil {
		return x.Sql
	}
	return ""
}

type ExplainSQLResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Explanation string `protobuf:"bytes,1,opt,name=explanation,proto3" json:"explanation,omitempty"`
}

func (x *ExplainSQLResponse) Reset() {
	*x = ExplainSQLResponse{}
	mi := &file_proto_vanna_vanna_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExplainSQLResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExplainSQLResponse) ProtoMessage() {}

func (x *ExplainSQLResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_vanna_vanna_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExplainSQLResponse.ProtoReflect.Descriptor instead.
func (*ExplainSQLResponse) Descriptor() ([]byte, []int) {
	return file_proto_vanna_vanna_proto_rawDescGZIP(), []int{5}
}

func (x *ExplainSQLResponse) GetExplanation() string {
	if x != nil {
		return x.Explanation
	}
	return ""
}

type TrainRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data []string `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"`
}

func (x *TrainRequest) Reset() {
	*x = TrainRequest{}
	mi := &file_proto_vanna_vanna_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TrainRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrainRequest) ProtoMessage() {}

func (x *TrainRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_vanna_vanna_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrainRequest.ProtoReflect.Descriptor instead.
func (*TrainRequest) Descriptor() ([]byte, []int) {
	return file_proto_vanna_vanna_proto_rawDescGZIP(), []int{6}
}

func (x *TrainRequest) GetData() []string {
	if x != nil {
		return x.Data
	}
	return nil
}

type TrainResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success bool   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *TrainResponse) Reset() {
	*x = TrainResponse{}
	mi := &file_proto_vanna_vanna_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TrainResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrainResponse) ProtoMessage() {}

func (x *TrainResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_vanna_vanna_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrainResponse.ProtoReflect.Descriptor instead.
func (*TrainResponse) Descriptor() ([]byte, []int) {
	return file_proto_vanna_vanna_proto_rawDescGZIP(), []int{7}
}

func (x *TrainResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *TrainResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_proto_vanna_vanna_proto protoreflect.FileDescriptor

var file_proto_vanna_vanna_proto_rawDesc = []byte{
	0x0a, 0x17, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x76, 0x61, 0x6e, 0x6e, 0x61, 0x2f, 0x76, 0x61,
	0x6e, 0x6e, 0x61, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x76, 0x61, 0x6e, 0x6e, 0x61,
	0x22, 0xae, 0x01, 0x0a, 0x12, 0x47, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x74, 0x65, 0x53, 0x51, 0x4c,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x69, 0x6f, 0x6e, 0x12, 0x40, 0x0a, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x78, 0x74, 0x18, 0x02,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x26, 0x2e, 0x76, 0x61, 0x6e, 0x6e, 0x61, 0x2e, 0x47, 0x65, 0x6e,
	0x65, 0x72, 0x61, 0x74, 0x65, 0x53, 0x51, 0x4c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x2e,
	0x43, 0x6f, 0x6e, 0x74, 0x65, 0x78, 0x74, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x07, 0x63, 0x6f,
	0x6e, 0x74, 0x65, 0x78, 0x74, 0x1a, 0x3a, 0x0a, 0x0c, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x78, 0x74,
	0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38,
	0x01, 0x22, 0x49, 0x0a, 0x13, 0x47, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x74, 0x65, 0x53, 0x51, 0x4c,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x73, 0x71, 0x6c, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x73, 0x71, 0x6c, 0x12, 0x20, 0x0a, 0x0b, 0x65, 0x78,
	0x70, 0x6c, 0x61, 0x6e, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0b, 0x65, 0x78, 0x70, 0x6c, 0x61, 0x6e, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x26, 0x0a, 0x12,
	0x56, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x65, 0x53, 0x51, 0x4c, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x73, 0x71, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x03, 0x73, 0x71, 0x6c, 0x22, 0x4a, 0x0a, 0x13, 0x56, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x65,
	0x53, 0x51, 0x4c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x19, 0x0a, 0x08, 0x69,
	0x73, 0x5f, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x69,
	0x73, 0x56, 0x61, 0x6c, 0x69, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x22, 0x25, 0x0a, 0x11, 0x45, 0x78, 0x70, 0x6c, 0x61, 0x69, 0x6e, 0x53, 0x51, 0x4c, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x73, 0x71, 0x6c, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x03, 0x73, 0x71, 0x6c, 0x22, 0x36, 0x0a, 0x12, 0x45, 0x78, 0x70, 0x6c, 0x61,
	0x69, 0x6e, 0x53, 0x51, 0x4c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x20, 0x0a,
	0x0b, 0x65, 0x78, 0x70, 0x6c, 0x61, 0x6e, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0b, 0x65, 0x78, 0x70, 0x6c, 0x61, 0x6e, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x22,
	0x22, 0x0a, 0x0c, 0x54, 0x72, 0x61, 0x69, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x04, 0x64,
	0x61, 0x74, 0x61, 0x22, 0x43, 0x0a, 0x0d, 0x54, 0x72, 0x61, 0x69, 0x6e, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x12, 0x18,
	0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x32, 0x91, 0x02, 0x0a, 0x0c, 0x56, 0x61, 0x6e,
	0x6e, 0x61, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x44, 0x0a, 0x0b, 0x47, 0x65, 0x6e,
	0x65, 0x72, 0x61, 0x74, 0x65, 0x53, 0x51, 0x4c, 0x12, 0x19, 0x2e, 0x76, 0x61, 0x6e, 0x6e, 0x61,
	0x2e, 0x47, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x74, 0x65, 0x53, 0x51, 0x4c, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x1a, 0x2e, 0x76, 0x61, 0x6e, 0x6e, 0x61, 0x2e, 0x47, 0x65, 0x6e, 0x65,
	0x72, 0x61, 0x74, 0x65, 0x53, 0x51, 0x4c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x44, 0x0a, 0x0b, 0x56, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x65, 0x53, 0x51, 0x4c, 0x12, 0x19,
	0x2e, 0x76, 0x61, 0x6e, 0x6e, 0x61, 0x2e, 0x56, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x65, 0x53,
	0x51, 0x4c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1a, 0x2e, 0x76, 0x61, 0x6e, 0x6e,
	0x61, 0x2e, 0x56, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x65, 0x53, 0x51, 0x4c, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x41, 0x0a, 0x0a, 0x45, 0x78, 0x70, 0x6c, 0x61, 0x69, 0x6e,
	0x53, 0x51, 0x4c, 0x12, 0x18, 0x2e, 0x76, 0x61, 0x6e, 0x6e, 0x61, 0x2e, 0x45, 0x78, 0x70, 0x6c,
	0x61, 0x69, 0x6e, 0x53, 0x51, 0x4c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x19, 0x2e,
	0x76, 0x61, 0x6e, 0x6e, 0x61, 0x2e, 0x45, 0x78, 0x70, 0x6c, 0x61, 0x69, 0x6e, 0x53, 0x51, 0x4c,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x32, 0x0a, 0x05, 0x54, 0x72, 0x61, 0x69,
	0x6e, 0x12, 0x13, 0x2e, 0x76, 0x61, 0x6e, 0x6e, 0x61, 0x2e, 0x54, 0x72, 0x61, 0x69, 0x6e, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x14, 0x2e, 0x76, 0x61, 0x6e, 0x6e, 0x61, 0x2e, 0x54,
	0x72, 0x61, 0x69, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x37, 0x5a, 0x35,
	0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x66, 0x65, 0x69, 0x63, 0x68,
	0x61, 0x69, 0x30, 0x30, 0x31, 0x37, 0x2f, 0x64, 0x6f, 0x63, 0x75, 0x6d, 0x65, 0x6e, 0x74, 0x2d,
	0x70, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x6f, 0x72, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f,
	0x76, 0x61, 0x6e, 0x6e, 0x61, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_vanna_vanna_proto_rawDescOnce sync.Once
	file_proto_vanna_vanna_proto_rawDescData = file_proto_vanna_vanna_proto_rawDesc
)

func file_proto_vanna_vanna_proto_rawDescGZIP() []byte {
	file_proto_vanna_vanna_proto_rawDescOnce.Do(func() {
		file_proto_vanna_vanna_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_vanna_vanna_proto_rawDescData)
	})
	return file_proto_vanna_vanna_proto_rawDescData
}

var file_proto_vanna_vanna_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_proto_vanna_vanna_proto_goTypes = []any{
	(*GenerateSQLRequest)(nil),  // 0: vanna.GenerateSQLRequest
	(*GenerateSQLResponse)(nil), // 1: vanna.GenerateSQLResponse
	(*ValidateSQLRequest)(nil),  // 2: vanna.ValidateSQLRequest
	(*ValidateSQLResponse)(nil), // 3: vanna.ValidateSQLResponse
	(*ExplainSQLRequest)(nil),   // 4: vanna.ExplainSQLRequest
	(*ExplainSQLResponse)(nil),  // 5: vanna.ExplainSQLResponse
	(*TrainRequest)(nil),        // 6: vanna.TrainRequest
	(*TrainResponse)(nil),       // 7: vanna.TrainResponse
	nil,                         // 8: vanna.GenerateSQLRequest.ContextEntry
}
var file_proto_vanna_vanna_proto_depIdxs = []int32{
	8, // 0: vanna.GenerateSQLRequest.context:type_name -> vanna.GenerateSQLRequest.ContextEntry
	0, // 1: vanna.VannaService.GenerateSQL:input_type -> vanna.GenerateSQLRequest
	2, // 2: vanna.VannaService.ValidateSQL:input_type -> vanna.ValidateSQLRequest
	4, // 3: vanna.VannaService.ExplainSQL:input_type -> vanna.ExplainSQLRequest
	6, // 4: vanna.VannaService.Train:input_type -> vanna.TrainRequest
	1, // 5: vanna.VannaService.GenerateSQL:output_type -> vanna.GenerateSQLResponse
	3, // 6: vanna.VannaService.ValidateSQL:output_type -> vanna.ValidateSQLResponse
	5, // 7: vanna.VannaService.ExplainSQL:output_type -> vanna.ExplainSQLResponse
	7, // 8: vanna.VannaService.Train:output_type -> vanna.TrainResponse
	5, // [5:9] is the sub-list for method output_type
	1, // [1:5] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_vanna_vanna_proto_init() }
func file_proto_vanna_vanna_proto_init() {
	if File_proto_vanna_vanna_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_vanna_vanna_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_vanna_vanna_proto_goTypes,
		DependencyIndexes: file_proto_vanna_vanna_proto_depIdxs,
		MessageInfos:      file_proto_vanna_vanna_proto_msgTypes,
	}.Build()
	File_proto_vanna_vanna_proto = out.File
	file_proto_vanna_vanna_proto_rawDesc = nil
	file_proto_vanna_vanna_proto_goTypes = nil
	file_proto_vanna_vanna_proto_depIdxs = nil
}
